version: "3.8"
# 我这个 docker compose 由几个服务组成
services:
  mysql8:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
#      - 初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
#      - 外部访问用 13316
      - 13316:3306

  redis:
    image: "bitnami/redis:latest"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'


  etcd:
    image: "bitnami/etcd:latest"
    container_name: webook-etcd-1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes  # 允许不使用认证
    ports:
      - "12379:2379"                  # 映射客户端访问端口
    volumes:
      - etcd-data:/etcd-data          # 持久化数据
    networks:
      - etcd_network

networks:
  etcd_network:
    driver: bridge

volumes:
  etcd-data: