name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Install wire
      run: go install github.com/google/wire/cmd/wire@latest

    - name: Generate wire code
      run: wire

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
